import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "concepts",
      "children": [
        {
          "slug": "endpoint-creator"
        },
        {
          "slug": "endpoints"
        },
        {
          "slug": "error-handling"
        },
        {
          "slug": "headers-and-cookies"
        },
        {
          "slug": "middleware"
        },
        {
          "slug": "openapi"
        },
        {
          "slug": "router"
        },
        {
          "slug": "rpc-client"
        }
      ]
    },
    {
      "slug": "api",
      "children": [
        {
          "slug": "exports"
        }
      ]
    },
    {
      "slug": "adapters",
      "children": [
        {
          "slug": "node"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
